name: pr

on:
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "emmylua.md"
      - "stylua.toml"
      - "todo.txt"
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        job:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          # - { os: windows-latest, target: x86_64-pc-windows-msvc }
          # - { os: macos-latest, target: x86_64-apple-darwin }
    runs-on: ${{ matrix.job.os }}
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
          echo "MSRV=$(sed -n 's/^rust-version = "\(.*\)"/\1/p' Cargo.toml)" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MSRV }}
          target: ${{ matrix.job.target }}
          components: clippy,rustfmt

      - name: Test
        run: cargo test --all-features

      - name: Lint
        run: cargo clippy --all-features

      - name: Format
        run: cargo fmt --check
